### ISSUE TITLE
Could you make the code public?

### ISSUE THREAD

**Issue by nonnoz** [mdarfay/Toycopter#1]
HI, Matthieu and Zoé! I am a computer science student, just like you. I was searching online to find some inspiration for my Computer Graphics coursework and I found your work. Your idea is very attractive and interesting. I am really interested in your project and I am wondering if it is possible for you to make the code public? It would be a lot of help. Anyway, I am very inspired by your project and hope I can also finish my project with high quality.

**Comment by mdarfay** [comment]
Hello, thanks for your kind message and your appreciation of our work. Unfortunately, we don't have the permission to make the code public. Indeed, important parts of our projects were provided by our teacher as part of Practical Works and guides for the global project. Thus, a lot of this code is still used currently for courses in our university and our teacher didn't want their code to be public. That's the reason why we can't make it available to everyone online.
Sorry for the inconvenience, hope you will be able to succeed in your course anyway!

**Comment by nonnoz** [comment]
> Hello, thanks for your kind message and your appreciation of our work. Unfortunately, we don't have the permission to make the code public. Indeed, important parts of our projects were provided by our teacher as part of Practical Works and guides for the global project. Thus, a lot of this code is still used currently for courses in our university and our teacher didn't want their code to be public. That's the reason why we can't make it available to everyone online. Sorry for the inconvenience, hope you will be able to succeed in your course anyway!

Thanks for your kind reply and encouragement :) Your YouTube  video has already inspired me a lot and appreciate your work. Thanks anyway!
